notify_on_join: true
messages:
  no_unclaimed_data: "You have no unclaimed player data."
  inventory_no_unclaimed: "You have no unclaimed inventory."
  inventory_already_claimed: "You have already claimed your inventory."
  inventory_claim_confirm: "You need to have enough space in your inventory to claim your old inventory."
  inventory_claimed: "You have claimed your inventory."
  xp_total_no_unclaimed: "You have no unclaimed experience."
  xp_total_already_claimed: "You have already claimed your experience."
  xp_total_claim_confirm: "Do you want to claim your %xp% xp?"
  xp_total_claimed: "You have claimed your experience."
  ender_items_no_unclaimed: "You have no unclaimed enderchest."
  ender_items_already_claimed: "You have already claimed your enderchest."
  ender_items_claim_confirm: "You need to have enough space in your inventory to claim your old enderchest."
  ender_items_claimed: "You have claimed your enderchest."
  items_amount: "(%amount% items)"
  items_list: "Items:"
  overflow_info: "Overflowing items will be dropped."
  confirm_button: "[Confirm]"
  no_console: "This command can only be executed by players."
  reload: "Config reloaded."
  no_permission: "You do not have permission to use this command."
  unclaimed_data: "You have unclaimed player data. claim it with /claimplayerdata."
  wrong_usage: "Usage: /claimplayerdata <inv|end|xp>"