messages:
  no_unclaimed_data: "You have no unclaimed player data."
  no_unclaimed_inventory: "You have no unclaimed inventory."
  no_unclaimed_xp: "You have no unclaimed experience."
  no_unclaimed_enderchest: "You have no unclaimed enderchest."
  claimed_inventory: "You have claimed your inventory."
  claimed_xp: "You have claimed your experience."
  claimed_enderchest: "You have claimed your enderchest."
  claim_inventory_confirm: "You need to have enough space in your inventory to claim your old inventory."
  claim_xp_confirm: "Do you want to claim your %xp% xp?"
  claim_enderchest_confirm: "You need to have enough space in your enderchest to claim your old enderchest."
  items amount: "(%amount% items)"
  items_list: "Items:"
  overflow_info: "Overflowing items will be dropped."
  confirm_button: "[Confirm]"
  no_console: "This command can only be executed by players."
  reload: "Config reloaded."
  no_permission: "You do not have permission to use this command."